#!/bin/bash

popup_powermenu() {
    eww open powermenu --toggle
}

popup_dashboard() {
    eww open dashboard --toggle
}

case "$1" in
    powmenu ) popup_powermenu;;
    dashboard) popup_dashboard ;;
    *)
        echo "Unkown action"
        exit 1
        ;;
esac
